update=2018 March 07, Wednesday 17:45:07
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../../Documents/kicad libraries/kicad-library-master/library;../../../Documents/kicad libraries/Opendous_KiCad_Libraries/library
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Addressable-Specialty
LibName31=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName32=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Automotive-Relays
LibName33=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Balun
LibName34=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Barrel-Audio-Connectors
LibName35=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName36=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName37=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName38=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName39=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Coaxial-Connectors-RF
LibName40=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Current-Transducers
LibName41=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_D-Sub-Connectors
LibName42=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName43=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName44=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName45=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName46=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName47=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_DC-DC-Converters
LibName48=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Digital-Isolators
LibName49=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName50=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName51=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName52=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Diodes-Zener-Single
LibName53=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName54=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Embedded-Microcontrollers
LibName55=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Encoders
LibName56=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName57=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName58=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Fixed-Inductors
LibName59=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Fuses
LibName60=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Gas-Sensors
LibName61=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName62=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Image-Sensors-Camera
LibName63=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName64=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName65=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName66=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName67=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Controllers
LibName68=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName69=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-I-O-Expanders
LibName70=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Modules
LibName71=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName72=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName73=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Interface-Specialized
LibName74=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_LED-Indication-Discrete
LibName75=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName76=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName77=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName78=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Linear-Comparators
LibName79=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName80=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Flip-Flops
LibName81=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName82=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Multivibrators
LibName83=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Shift-Registers
LibName84=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName85=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName86=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName87=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName88=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName89=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName90=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Memory
LibName91=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Microphones
LibName92=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName93=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks
LibName94=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName95=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName96=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName97=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Navigation-Switches-Joystick
LibName98=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName99=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName100=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName101=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName102=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName103=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Logic-Output
LibName104=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName105=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName106=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Oscillators
LibName107=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName108=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Chargers
LibName109=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Management
LibName110=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName111=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName112=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Gate-Drivers
LibName113=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-LED-Drivers
LibName114=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName115=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName116=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName117=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName118=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName119=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Supervisors
LibName120=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Thermal-Management
LibName121=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName122=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Reference
LibName123=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName124=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName125=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName126=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName127=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName128=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName129=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Programmable-Oscillators
LibName130=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Pushbutton-Switches
LibName131=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName132=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Reed-Relays
LibName133=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Resistor-Networks-Arrays
LibName134=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Amplifiers
LibName135=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Antennas
LibName136=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Demodulators
LibName137=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Detectors
LibName138=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName139=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Receivers
LibName140=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Switches
LibName141=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-ICs
LibName142=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-Modules
LibName143=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RF-Transmitters
LibName144=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName145=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName146=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName147=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName148=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Slide-Switches
LibName149=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Solid-State-Relays
LibName150=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Specialized-ICs
LibName151=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Specialized-Sensors
LibName152=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Surge-Suppression-ICs
LibName153=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Tactile-Switches
LibName154=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName155=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName156=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName157=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Thyristors-SCRs
LibName158=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Thyristors-TRIACs
LibName159=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Toggle-Switches
LibName160=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName161=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName162=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName163=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName164=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName165=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName166=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName167=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Transistors-JFETs
LibName168=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_Trimmer-Potentiometers
LibName169=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_TVS-Diodes
LibName170=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_TVS-Mixed-Technology
LibName171=/Users/viljami/Documents/kicad libraries/digikey-kicad-library/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName172=opendous
LibName173=/Users/viljami/Documents/kicad libraries/TMC2130
LibName174=/Users/viljami/Documents/kicad libraries/Infineon
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
